### ISSUE TITLE
How to use platform-atmelsam with framework-cmsis-atmel?

### ISSUE THREAD

**Issue by RudolphRiedel** [platformio/platform-atmelsam#103] opened 2020-04-05 08:44 UTC
I am trying to use atmelsam but all boards are using one of the Arduino or Arduino-like frameworks.
Only samc21_xpro is an exception but only in that it has no frameworks defined - how is this supposed to work?

I can add a custom board file to my project/board and add all the includes manually to project/include.
This kind of works but not only does it defeat the purpose of PlatformIO a bit, I am pretty sure it does not even work since I still have no startup-code and at least the stack is not set up.

But as soon as I add "framework = cmsis-atmel" to my platformio.ini, platformio bombs out:

 - toolchain-gccarmnoneeabi 1.70201.0 (7.2.1)
AssertionError: :
  File "C:\users\ich\.platformio\penv\lib\site-packages\platformio\builder\main.py", line 156:
    env.SConscript("$BUILD_SCRIPT")
  File "C:\Users\Ich\.platformio\packages\tool-scons\script\..\engine\SCons\Script\SConscript.py", line 597:       
    return _SConscript(self.fs, *files, **subst_kw)
  File "C:\Users\Ich\.platformio\packages\tool-scons\script\..\engine\SCons\Script\SConscript.py", line 286:       
    exec(compile(scriptdata, scriptname, 'exec'), call_stack[-1].globals)
  File "C:\users\ich\.platformio\platforms\atmelsam\builder\main.py", line 127:
    target_elf = env.BuildProgram()
  File "C:\Users\Ich\.platformio\packages\tool-scons\script\..\engine\SCons\Environment.py", line 219:
    return self.method(*nargs, **kwargs)
  File "C:\users\ich\.platformio\penv\lib\site-packages\platformio\builder\tools\platformio.py", line 61:
    env.ProcessProgramDeps()
  File "C:\Users\Ich\.platformio\packages\tool-scons\script\..\engine\SCons\Environment.py", line 219:
    return self.method(*nargs, **kwargs)
  File "C:\users\ich\.platformio\penv\lib\site-packages\platformio\builder\tools\platformio.py", line 118:
    env.BuildFrameworks(env.get("PIOFRAMEWORK"))
  File "C:\Users\Ich\.platformio\packages\tool-scons\script\..\engine\SCons\Environment.py", line 219:
    return self.method(*nargs, **kwargs)
  File "C:\users\ich\.platformio\penv\lib\site-packages\platformio\builder\tools\platformio.py", line 330:
    SConscript(env.GetFrameworkScript(f), exports="env")
  File "C:\Users\Ich\.platformio\packages\tool-scons\script\..\engine\SCons\Environment.py", line 219:
    return self.method(*nargs, **kwargs)
  File "C:\users\ich\.platformio\penv\lib\site-packages\platformio\builder\tools\pioplatform.py", line 56:
    assert p.frameworks and framework in p.frameworks
=========================================== [FAILED] Took 1.19 seconds

**Comment by valeros** [comment] 2020-04-06 10:20
Closing as duplicate of #80

There is no support for `CMSIS` framework at the moment. The empty framework field means that user is responsible for bootstrapping a working firmware (including startup routine, linker scripts, etc).

**Closed by valeros** 2020-04-06 10:20 UTC
