### ISSUE TITLE
Add board request: Sodaq SARA 

### ISSUE THREAD

**Issue by Midnight28** [platformio/platform-atmelsam#35] opened 2018-09-27 06:51 UTC
Hello!
I would like to ask you to add the Sodaq SARA board, link:

https://support.sodaq.com/sodaq-one/sodaq-sara-r410m/

Your work is appreciated a lot, thank you very much!

**Comment by ivankravets** [comment] 2018-10-10 19:18
Duplicate of https://github.com/platformio/platform-atmelsam/issues/34

**Closed by ivankravets** 2018-10-10 19:18 UTC

**Comment by ivankravets** [comment] 2018-10-10 19:57
Please re-test with upstream version. Does it work for you?
- http://docs.platformio.org/en/latest/platforms/atmelsam.html#upstream
