### ISSUE TITLE
Board Request Arduino  MKRWAN 1310 

### ISSUE THREAD

**Issue by 03sarath** [platformio/platform-atmelsam#88] opened 2019-12-08 18:15 UTC
Hello,

Requesting to add new release from Arduino  **Arduino MKRWAN 1310**  low power LoRa module.

**Comment by ivankravets** [comment] 2019-12-30 10:37
Duplicate of https://github.com/platformio/platform-atmelsam/issues/86

**Closed by ivankravets** 2019-12-30 10:37 UTC
