### ISSUE TITLE
Feature Request:  Handy port finder for recovering after botched upload

### ISSUE THREAD

**Issue by SRGDamia1** [platformio/platform-atmelsam#14] opened 2017-05-16 17:43 UTC
The Arduino IDE allows a port search/reset mid-upload to recover the serial port after uploading a botched sketch.  This feature is super handy and would be nice to have in PIO.

Here's a description in Adafruit's FAQ:  https://learn.adafruit.com/adafruit-feather-32u4-adalogger/faq#faq-3

The same functionality applies to the 32u4 and SAMD21/M0 (and I assume other boards with separate programming port numbers).

**Comment by ivankravets** [comment] 2018-02-10 15:27
Duplicate of https://github.com/platformio/platform-atmelsam/issues/13

**Closed by ivankravets** 2018-02-10 15:27 UTC
Labels: help wanted
